# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "3.2"


virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libatlas-base-dev gfortran
 - sudo apt-get build-dep -qq python3-numpy
 - sudo apt-get build-dep -qq python3-scipy
 - sudo apt-get install -qq python-snappy libsnappy-dev libsnappy1
 - pip install -q numpy
 - pip install -U git+https://github.com/vmalloc/mongomock.git

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U -r requirements.txt --use-mirrors

# command to run tests, e.g. python setup.py test
script: python setup.py test